"""phase-2 sessions

Revision ID: 1cf7249a4bc3
Revises: 79ea9cc51971
Create Date: 2026-07-03 08:03:00.472151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf7249a4bc3'
down_revision: Union[str, None] = '79ea9cc51971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('dataset_id', sa.Text(), nullable=False),
    sa.Column('profile_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # SQLite cannot ALTER-add a foreign key in place — use batch mode so the
    # nullable session_id column + FK apply cleanly on an existing DB.
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Text(), nullable=True))
        batch_op.create_foreign_key(
            'fk_runs_session_id_sessions', 'sessions', ['session_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_runs_session_id_sessions', type_='foreignkey')
        batch_op.drop_column('session_id')
    op.drop_table('sessions')
    # ### end Alembic commands ###
