"""phase-2 chat_turns

Revision ID: a2675ad41d3c
Revises: 3074000ec151
Create Date: 2026-07-07 15:53:42.439675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2675ad41d3c'
down_revision: Union[str, None] = '3074000ec151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_turns',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('engagement_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_turns')
    # ### end Alembic commands ###
